name: Feature Request
description: Request a new feature for a package.
labels: Enhancement
body:
    - type: markdown
      attributes:
          value: Visit our [Guilded Server](https://guildedts.js.org/support) for general support.
    - type: dropdown
      attributes:
          label: Package
          description: The package the feature is for.
          options:
              - builders
              - framework
              - guilded-api-typings
              - guilded.ts
              - rest
              - util
              - ws
      validations:
          required: true
    - type: textarea
      attributes:
          label: Description
          description: Describe the feature in as much detail as possible.
          placeholder: Guilded recently added a new feature...
      validations:
          required: true
    - type: textarea
      attributes:
          label: Solution
          description: A detailed description of how you would want to implement the feature.
          placeholder: We could do something like...
      validations:
          required: true
    - type: textarea
      attributes:
          label: Alternative Solutions
          description: Any alternative solutions that you may have considered.
