name: Deploy documentation
on:
    push:
        branches: [ master ]
jobs:
    gendocs:
        name: Deploy documentation
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Install node
                uses: actions/setup-node@v3
                with:
                    node-version: 18
            -   name: Install dependencies
                run: yarn
            -   name: Build packages
                run: yarn build
            -   name: Generate documentation
                run: yarn docs
            -   name: Commit changes
                uses: cpina/github-action-push-to-another-repository@main
                env:
                    API_TOKEN_GITHUB: ${{ secrets.API_GITHUB_TOKEN }}
                with:
                    source-directory: docs
                    destination-github-username: guildedts
                    destination-repository-name: docs
                    user-name: github-actions[bot]
                    user-email: 41898282+github-actions[bot]@users.noreply.github.com
