name: Deploy documentation
on:
    push:
        branches: [master]
        paths:
            - 'packages/*/src/**/*.ts'
            - '!docs'
jobs:
    gendocs:
        name: Deploy documentation
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: yarn install
            - name: Build packages
              run: yarn build
            - name: Generate documentation
              run: yarn docs
            - name: Configure git
              run: |
                  git config user.name github-actions[bot]
                  git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            - name: Commit changes
              run: |
                  git add docs
                  git commit -m "workflow: Generate docs"
                  git push origin main
