name: Prepare
on: push
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
          uses: actions/setup-node@v3
          with:
            node-version: '16'

      - name: Install dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Prepare packages
        run: yarn prepare

      - name: Configure git
        run: |
          git config user.name "Preparation bot"
          git config user.email "<>"

      - name: Commit changes
        run: |
          git add docs
          git commit -m "workflow: Prepare packages"
          git push origin main
