name: Release Packages
on:
    push:
        branches: [main]
jobs:
    release:
        name: Release Packages
        runs-on: ubuntu-latest
        outputs:
            published: ${{ steps.changesets.outputs.published }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install PNPM
              uses: pnpm/action-setup@v2
            - name: Install Dependencies
              run: pnpm i --ignore-scripts
            - name: Create Release Pull Request or Publish to NPM
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: pnpm run publish
                  version: pnpm run version
                  title: 'chore: release packages'
                  commit: 'chore: release packages'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    release-dev:
        name: Release Packages (dev)
        runs-on: ubuntu-latest
        needs: release
        if: needs.release.outputs.published == 'false'
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install PNPM
              uses: pnpm/action-setup@v2
            - name: Install Dependencies
              run: pnpm i --ignore-scripts
            - name: Version Packages
              run: pnpm run version:dev
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Publish to NPM
              run: pnpm run publish:dev
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    docs:
        name: Deploy Documentation
        runs-on: ubuntu-latest
        # needs: release
        # if: needs.release.outputs.published == 'true'
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install PNPM
              uses: pnpm/action-setup@v2
            - name: Install Dependencies
              run: pnpm i
            - name: Generate Documentation
              run: pnpm run docs
            - name: Commit Changes
              uses: cpina/github-action-push-to-another-repository@main
              env:
                  API_TOKEN_GITHUB: ${{ secrets.API_GITHUB_TOKEN }}
              with:
                  source-directory: docs
                  destination-github-username: guildedts
                  destination-repository-name: docs
                  user-name: github-actions[bot]
                  user-email: 41898282+github-actions[bot]@users.noreply.github.com
