name: Release
on:
    push:
        branches: [ master ]
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Install Node
                uses: actions/setup-node@v3
                with:
                    node-version: 18
            -   name: Install Dependencies
                run: yarn
            -   name: Create Release Pull Request or Publish to NPM
                uses: changesets/action@master
                with:
                    publish: yarn publish
                    version: yarn version
                    title: 'chore: release'
                    commit: 'chore: release'
                env:
                    GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
                    NPM_TOKEN: ${{ secrets.API_NPM_TOKEN }}
